name: hustack Image CI

on:
  push:
    branches:
      - main
    paths:
      - "hustack-backend/baseweb/**"
  pull_request:
    branches:
      - main
    paths:
      - "hustack-backend/baseweb/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create file appication.yml
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: "application.yml"
          fileDir: "./hustack-backend/baseweb/src/main/resources/"
          encodedString: ${{ secrets.HUSTACK_B64_SECRET }}
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: leanhtuan/hustack
          directory: "hustack-backend/baseweb/"
          registry: docker.io
          #multiPlatform: true
          #platform: linux/amd64,linux/arm64
          dockerfile: "hustack-backend/baseweb/Dockerfile"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          addLatest: true
      - name: Remove config file
        uses: JesseTG/rm@v1.0.2
        with:
          path: "./hustack-backend/baseweb/src/main/resources/application.yml"
